# Generated by Django 2.2 on 2021-04-02 15:58

from django.db import migrations, models
import register_login_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, validators=[register_login_app.models.validateLengthGreaterThanTwo])),
                ('last_name', models.CharField(max_length=45, validators=[register_login_app.models.validateLengthGreaterThanTwo])),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
