# Generated by Django 2.2 on 2021-03-28 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_app', '0002_auto_20210328_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message_from', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post_message', to='login_app.User')),
                ('message_to', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='get_message', to='login_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comment', to='login_app.User')),
                ('comment_to', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='user_app.Message')),
            ],
        ),
    ]
