# Generated by Django 2.2 on 2021-04-07 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
