# Generated by Django 2.2 on 2021-03-24 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite_books_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='users_who_like',
            field=models.ManyToManyField(null=True, related_name='liked_books', to='login_app.Users'),
        ),
    ]
