# Generated by Django 2.2 on 2021-03-13 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ninjas',
            old_name='author',
            new_name='dojo',
        ),
    ]
